### ISSUE TITLE
on Ctrl-C  -- kill child not itself

### ISSUE THREAD

**Issue by yarikoptic** [con/duct#184]
Currently

```
❯ duct  dd if=/dev/zero of=/dev/null
2024-09-20T10:26:35-0400 [INFO    ] con-duct: duct is executing 'dd if=/dev/zero of=/dev/null'...
2024-09-20T10:26:35-0400 [INFO    ] con-duct: Log files will be written to .duct/logs/2024.09.20T10.26.35-184161_
^C^C^CTraceback (most recent call last):
  File "/usr/lib/python3.12/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 2053, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 2011, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/proj/CON/duct/venvs/dev3.12/bin/duct", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yoh/proj/CON/duct/src/con_duct/__main__.py", line 883, in main
    sys.exit(execute(args))
             ^^^^^^^^^^^^^
  File "/home/yoh/proj/CON/duct/src/con_duct/__main__.py", line 972, in execute
    process.wait()
  File "/usr/lib/python3.12/subprocess.py", line 1277, in wait
    self._wait(timeout=sigint_timeout)
  File "/usr/lib/python3.12/subprocess.py", line 2047, in _wait
    time.sleep(delay)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1624, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

so we are pretty much killing ourselves and do not provide summary etc.  I think we should

- intercept Ctrl-C (I think it is possible, offlineimap does it) and unless 3 times consecutive within e.g. 3 seconds, we instead "peacefully" killing the underlying child process instead and "proceed" normally printing its killed exit code and summary

**Comment by asmacdo** [comment]
+100

**Comment by asmacdo** [comment]
offlineimap does this using sig_handlers https://github.com/OfflineIMAP/offlineimap3/blob/db347452273bb0f1b1a8ea952f6fb46cf95fedbf/offlineimap/init.py#L482
and events https://github.com/OfflineIMAP/offlineimap3/blob/db347452273bb0f1b1a8ea952f6fb46cf95fedbf/offlineimap/accounts.py#L452

That general approach should work for us also.

I propose this interface:

  - First SIGTERM: send SIGTERM to the parent process that duct is executing
  - Second SIGTERM: send SIGKILL to the parent process that duct is executing
  - Third SIGTERM: immediately exit, even if we are leaving the process running

**Comment by yarikoptic** [comment]
I think we need to prioritize this issue -- I ran into a number of situations whenever I was left with such run away processes.
